### ISSUE TITLE
Tests for lseguid_sticky()?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#1]
Please add a few tests for `lseguid_sticky()` to the Python code.  I need them to validate my R implementation of it.

**Comment by BjornFJohansson** [comment]
done!

**Comment by HenrikBengtsson** [comment]
Where? I cannot find it?

**Comment by HenrikBengtsson** [comment]
Bump - where?

**Comment by BjornFJohansson** [comment]
This is now obsolete due to redefinition of the checksums themselves.
