### ISSUE TITLE
HYGIENE: Don't add binaries to repo

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#11]
We should add executables to the repository, because:

* a git repository should basically just hold _source ode_ - not artifacts such as executables.
* it's not considered safe to download random executables, so we shouldn't lure to use an executable part of a git repo.
* executable are much bigger than source code and will inflate the git repo size.
* there are other ways to distribute executables and packages, e.g. PyPI, CRAN, as well as GitHub releases.

So,

* [ ] [Rust/duvalrust](https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/main/Rust/duvalrust)

should be removed.

**Comment by HenrikBengtsson** [comment]
Same arguments go for documentation artifacts, i.e. documentation that is generated from the existing source code.  Because of this, I argue `Python/docs/_build/` should not be in the git repo.

**Comment by HenrikBengtsson** [comment]
A friendly reminder about this one

**Comment by HenrikBengtsson** [comment]
Ping

**Comment by BjornFJohansson** [comment]
Think this is fixed, can not see any binary or build files.
