### ISSUE TITLE
Are those 3'/5' sequences really valid?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#13]
Are the following really valid?

* Forgetting prime after 3 or 5, e.g. `3-` and `5-`
* Space after or before `3'` or `5'`, e.g. `3'-  ` and `  -5'`

Is there a formal reference for this?

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/9eeb6be3b55c8ba4f12e07a086c39115894b5ca9/Python/tests.py#L79-L81

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/9eeb6be3b55c8ba4f12e07a086c39115894b5ca9/Python/tests.py#L110-L112

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/9eeb6be3b55c8ba4f12e07a086c39115894b5ca9/Python/tests.py#L131-L133

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/9eeb6be3b55c8ba4f12e07a086c39115894b5ca9/Python/tests.py#L160-L162

**Comment by HenrikBengtsson** [comment]
Similarly to https://github.com/MetabolicEngineeringGroupCBMA/seguid/issues/5#issuecomment-1773982959, being too lax about the input, just opens up to having mistakes and typos in input data without catching them.

**Comment by BjornFJohansson** [comment]
The current `tuple_from_repr` only accepts space and sep:

```
def tuple_from_repr(
    rpr: str,
    table: dict = COMPLEMENT_TABLE,
    space: str = "-",
    sep: str = "\n"
) -> tuple:
```
