### ISSUE TITLE
COMPLEMENT_TABLE -> table

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#16]
`COMPLEMENT_TABLE` should be `table` in:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/2ed17694f309405736183afe2b94ad99fe967b36/Python/seguid.py#L111C33-L111C49

**Comment by BjornFJohansson** [comment]
This is what we now have in current version.
