### ISSUE TITLE
Python: doctest code at the end of files?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#20]
What is:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/bb2c4420992c462905e595a203155a692aad1507/Python/src/seguid/chksum.py#L306-L308

at the end of the files?

Can it be removed?

**Comment by BjornFJohansson** [comment]
Yes! It is there to enable execution of the file itself as a script in which case it runs the doctests in the file.

**Comment by HenrikBengtsson** [comment]
If so, it's missing from some files;

```sh
$ grep --files-without-match doctest *.py  
__init__.py
manip.py
tables.py
```

**Comment by HenrikBengtsson** [comment]
> Yes! It is there to enable execution of the file itself as a script in which case it runs the doctests in the file.

Could it be that there's another solution or way to specify that, because it's (a) easy to forget, (b) clutters the code, (c) complicates code-coverage estimation?

**Comment by HenrikBengtsson** [comment]
Per call on 2023-12-16: I removed all doctest code at the end of the source files. There are other ways to run such tests.
