### ISSUE TITLE
ReadTheDocs: How is updated?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#22]
How is https://seguid.readthedocs.io/ updated?  Can it be done via GitHub Actions?

**Comment by HenrikBengtsson** [comment]
Q2. Can `.readthedocs.yaml` be moved to `Python/.readthedocs.yaml`?

**Comment by BjornFJohansson** [comment]
"The .readthedocs.yaml file should be placed in the top-most directory of your project’s repository."

https://docs.readthedocs.io/en/stable/config-file/index.html#where-to-put-your-configuration-file

So it seems not.

**Comment by BjornFJohansson** [comment]
Regarding GH action, I think it watches the repo and update automatically, given the correct settings.
