### ISSUE TITLE
Python: Inconsistent test-data file names

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#23]
Inconsistent test-data file names:

* puc19.txt
* pUC19msg.txt

Should it be `puc` or `pUC`?

**Comment by BjornFJohansson** [comment]
pUC is better

**Comment by BjornFJohansson** [comment]
done and added a readme in the test file dir

**Comment by HenrikBengtsson** [comment]
I've renamed the files in the R package accordingly.
