### ISSUE TITLE
Python: Document test-data files

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#24]
What is the source of the files:

```sh
$ tree Python/tests/test_data/
Python/tests/test_data/
├── M13msg.txt
├── M13.txt
├── NC_003287_2.gb
├── pUC19msg.txt
└── puc19.txt

0 directories, 5 files
```

?

How were they downloaded?

I think adding a `Python/tests/test_data/README.md` would be useful.

**Comment by BjornFJohansson** [comment]
Readme is a good idea

**Comment by BjornFJohansson** [comment]
rename files to indicate type (DNA...) and rotation. remove msg files, use checksum instead.

**Comment by BjornFJohansson** [comment]
Now documented in README
