### ISSUE TITLE
CLI: A draft for an API

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#25]
Imagine someone wants to use all this from the shell.  I think each language should implement the same, consistent CLI, e.g.

```sh
$ echo "AT" | python -m seguid 
seguid:Ax/RG6hzSrMEEWoCO1IWMGska+4

$ echo "AT" | Rscript -e seguid::seguid
seguid:Ax/RG6hzSrMEEWoCO1IWMGska+4

$ echo "AT" | seguid 
seguid:Ax/RG6hzSrMEEWoCO1IWMGska+4
```

The last example uses a generic `seguid` command.  This could be a shell script calling `python -m seguid` internally, or part of the C/Rust implementation.  Either way, below are some examples how a user could the CLI API (it's just a sketch for now):

```sh
$ echo "AT" | seguid
seguid:Ax/RG6hzSrMEEWoCO1IWMGska+4

$ echo "AT" | seguid --type="seguid"  ## default
seguid:Ax/RG6hzSrMEEWoCO1IWMGska+4
```

```sh
$ echo "AT" | seguid --type="slseguid"
slseguid:Ax_RG6hzSrMEEWoCO1IWMGska-4
```

```sh
$ seguid --type="scseguid" M13.txt
scseguid:aAjgnsF9cPI6cu8IQ81sYnstVzU
```

```sh
$ echo "-AT\nAT-" | seguid --type="dlseguid"
dlseguid:AWD-dt5-TEua8RbOWfnctJIu9nA

## Using a Bash Here Document ("heredoc")
$ seguid --type="dlseguid" << _eof_
-AT
AT-
_eof_
dlseguid:AWD-dt5-TEua8RbOWfnctJIu9nA
```

**Comment by HenrikBengtsson** [comment]
DECISION 2023-12-19: 

* [ ] HB will create CLI tests (using [Bats](https://github.com/bats-core/bats-core)) to test the CLI API, which will also help define it

**Comment by BjornFJohansson** [comment]
This could be solved for Python using a __main__.py file in the package.
All examples I saw only call one function, so not sure how to solve this.

**Comment by HenrikBengtsson** [comment]
> This could be solved for Python using a **main**.py file in the package. All examples I saw only call one function, so not sure how to solve this.

See https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/main/r/tests/cli.bats for example of single function API.  In R, one can also call individual functions, so I've added that CLI API too.

**Comment by HenrikBengtsson** [comment]
I've prepared the Python implementation with tests for the CLI API, cf. https://github.com/MetabolicEngineeringGroupCBMA/seguid/commit/1a401dc389a0687becddeb384505ac419ec26685.  When implemented, it's just to remove one line in the test script.  The test script is the same used for R.

**Comment by HenrikBengtsson** [comment]
Implemented CLI for Python;

```sh
$ python -m seguid --type=seguid <<< 'AACGT'
seguid:JJfufeYcSKefv14hxcooIuQJBsk

$ python -m seguid --type=slseguid <<< 'AACGT'
slseguid:JJfufeYcSKefv14hxcooIuQJBsk

$ python -m seguid --type=scseguid <<< 'AACGT'
scseguid:JJfufeYcSKefv14hxcooIuQJBsk

$ python -m seguid --type=dlseguid <<< $'AACGT\nTTGCA'
dlseguid:tYeHZYwxQGDHTqGDcrebERag0AU

$ python -m seguid --type=dcseguid <<< $'AACGT\nTTGCA'
dcseguid:tYeHZYwxQGDHTqGDcrebERag0AU
```

**Comment by BjornFJohansson** [comment]
Perfa!
