### ISSUE TITLE
Python: What happens if we use `space = " "` or `space = "A"` in tuple_from_repr()?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#26]
Q1. Does the current implementation of `tuple_from_repr()` handle the case when `space` is a whitespace character, e.g. `space = " "`?

Q2. Does it handle the case when you pass a symbol part of the table, e.g. a DNA symbol?

I think it's worth adding a few tests using different `space` characters, e.g.

* [ ] `space = "-"` # default
* [ ] `space = "."` # a custom character
* [ ] `space = " "`  # a whitespace character
* [ ] `space = "A"` # a symbol part of the table

**Comment by BjornFJohansson** [comment]
Whitespace ASCII 32 confuses the tuple_from_repr function, added an assert to prohibit this.
space = "A" does not work, added assert to prohibit space in the alphabet used.

**Comment by HenrikBengtsson** [comment]
It could be worth adding unit tests asserting it's caught as an error.  This would prevent us from introducing a bug in the future.
