### ISSUE TITLE
Python: How is 'whitespace' in tuple_from_repr() used?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#27]
In `tuple_from_repr()`:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/880a4e7245b02f4fb0898fc2553d68de1326587f/Python/src/seguid/reprutils.py#L50

you use `whitespace`.  How is that used?

**Comment by BjornFJohansson** [comment]
removed
