### ISSUE TITLE
TESTS: Add tests from examples

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#28]
The example:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/f15fd6c7323f8b2e2e381fcfa78f56033693b4fd/Python/src/seguid/chksum.py#L245-L249

illustrates that swapping `watson` and `crick` with the same `overhang` makes no difference.  I think this could be added as a formal unit test.

Are there more things in the doc examples that can be added as unit tests?

**Comment by BjornFJohansson** [comment]
added this and some more.
