### ISSUE TITLE
ROBUSTNESS: Test all functions with extreme cases

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#30]
We should write unit tests that test all functions with extreme input, e.g. empty input.

For example,

```sh
$ python -c "from seguid.manip import min_rotation_py; print(min_rotation_py(''))"
None
```

**Comment by BjornFJohansson** [comment]
min_rotation_py now returns 0 for empty string, same as pydivsufsort import min_rotation
