### ISSUE TITLE
TEST: Add missing test for dcseguid()

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#34]
The true statement of the following if-else statement in `dcseguid()` is not tested by the unit tests;

```py
    ## Keep the "minimum" of the two variants
    if watson_min < crick_min:
        w = watson_min
    else:
        w = crick_min
```

Source: https://app.codecov.io/gh/MetabolicEngineeringGroupCBMA/seguid/blob/main/Python%2Fsrc%2Fseguid%2Fchksum.py

* [x] R
* [ ] Python

**Comment by HenrikBengtsson** [comment]
I've added a "symmetric" check for this to R:

```r
truth <- "dcseguid:tYeHZYwxQGDHTqGDcrebERag0AU"
stopifnot(dcseguid("ACGTT", "AACGT") == truth)
stopifnot(dcseguid("AACGT", "ACGTT") == truth)
```

**Comment by BjornFJohansson** [comment]
added
