### ISSUE TITLE
Python: Purpose of with warnings.catch_warnings() with respect to pydivsufsort?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#35]
What's the purpose of:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/0766c8e1acd35c527fb69870d59e85c1eb980e5e/Python/src/seguid/config.py#L17-L18

in

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/0766c8e1acd35c527fb69870d59e85c1eb980e5e/Python/src/seguid/config.py#L15-L20

I'd like to replace that with:

```py
    elif which == "pydivsufsort":
        from pydivsufsort import min_rotation as min_rotation_pydivsufsort
        _min_rotation=min_rotation_pydivsufsort
```

**Comment by BjornFJohansson** [comment]
pydivsufsort min_rotation expects bytestring, warns if given string
