### ISSUE TITLE
ROBUSTNESS: Assert that locale does not affect results, specifically for min_rotation()

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#37]
Letters are ordered differently depending on the current [locale](https://en.wikipedia.org/wiki/Locale_(computer_software)), e.g.

```sh
$ (export LC_COLLATE="C"; [[ "z" < "t" ]] && echo "true" || echo "false")  
false

$ (export LC_COLLATE="en_US.utf8"; [[ "z" < "t" ]] && echo "true" || echo "false")  
false

$ (export LC_COLLATE="et_EE.utf8"; [[ "z" < "t" ]] && echo "true" || echo "false")  
true
```

Also, upper- and lower-case letters are ordered differently in different locales, e.g.

```sh
$ (export LC_COLLATE="C"; printf "%s\n" {A..Z} {a..z} | sort | tr $'\n' ' ')
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z a b c d e f g h i j k l m n o p q r s t u v w x y z

$ (export LC_COLLATE="en_US.utf8"; printf "%s\n" {A..Z} {a..z} | sort | tr $'\n' ' ')
a A b B c C d D e E f F g G h H i I j J k K l L m M n N o O p P q Q r R s S t T u U v V w W x X y Y z Z

(export LC_COLLATE="et_EE.utf8"; printf "%s\n" {A..Z} {a..z} | sort | tr $'\n' ' ')
A a B b C c D d E e F f G g H h I i J j K k L l M m N n O o P p Q q R r S s Z z T t U u V v W w X x Y y
```

We need to make sure that `min_rotation()` is not affected by these differences; it would be a nightmare if users would produce different checksums for the same input.

**Comment by HenrikBengtsson** [comment]
The current R implementation is affected this the locale;

```sh
$ LC_COLLATE="C" Rscript -e "seguid:::min_rotation('tz')"
[1] 0
$ LC_COLLATE="en_US.utf8" Rscript -e "seguid:::min_rotation('tz')"
[1] 0
$ LC_COLLATE="et_EE.utf8" Rscript -e "seguid:::min_rotation('tz')"
[1] 1
```

It looks like the Python implementation is not, e.g.

```sh
$ LC_COLLATE="en_US.utf8" python -c "from seguid.manip import min_rotation_py; print(min_rotation_py('actgACTG'))"
4

$ LC_COLLATE="C" python -c "from seguid.manip import min_rotation_py; print(min_rotation_py('actgACTG'))"
4

$ LC_COLLATE="et_EE.utf8" python -c "from seguid.manip import min_rotation_py; print(min_rotation_py('actgACTG'))"
4
```

OTH, the "min rotation" implementations gives different results in R and Python, so something is up, and the definition of "min rotation" needs to be more specific.

**Comment by HenrikBengtsson** [comment]
I wonder if:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/bc38a357751582a642d479cfa3fcdaf9d544bad4/Python/src/seguid/manip.py#L137

achieves something like:

```sh
$ LC_COLLATE="C" Rscript -e 'x <- c("\u0054", "\u005A"); y <- as.integer(charToRaw(paste0(x, collapse = ""))); o <- order(y); x[o]'
[1] "T" "Z"

$ LC_COLLATE="en_US.utf8" Rscript -e 'x <- c("\u0054", "\u005A"); y <- as.integer(charToRaw(paste0(x, collapse = ""))); o <- order(y); x[o]'
[1] "T" "Z"

$ LC_COLLATE="et_EE.utf8" Rscript -e 'x <- c("\u0054", "\u005A"); y <- as.integer(charToRaw(paste0(x, collapse = ""))); o <- order(y); x[o]'
[1] "T" "Z"
```

That is, if coerces letters into UTF-8 unicode representations (e.g. `T` -> `\u0054`, and `Z` -> `\u005A`), then coerces that into integers (`\u0054` -> `\x0054` -> 84, and `\u005A` -> `\x005A` -> 90), and then operates on integers instead of characters.

**Comment by HenrikBengtsson** [comment]
DECISION on 2023-12-19: Take a conservative approach and only allow for a-z and A-Z for now. Add this as an assertion to `assert_in_alphabet()`.

**Comment by BjornFJohansson** [comment]
The R hardcodes the space character "-" afaik. Will not work if user changes this.

**Comment by HenrikBengtsson** [comment]
> The R hardcodes the space character "-" afaik. Will not work if user changes this.

Yes, agree.  This begs the question: Should we expose the  `space` argument to the end-user?  Right now we don't - AFAIU, `tuple_from_repr()` is not part of the "public" API. 

I'd vote the conservative approach and say "no". The fewer things with expose/export, the fewer things the package/API can be "misused" without our knowledge.  Note exposing `space`, is effectively the same as saying we're hardcoding it to be `space = "-"`.

**Comment by HenrikBengtsson** [comment]
Oh, this also affects

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/d04159883df26b75eb55c4c009b85c562605f8ea/r/R/chksum.R#L137

so that comparison also needs to be guarded against this.

**Comment by HenrikBengtsson** [comment]
R: I'm now comparing `(watson_min < crick_min)` using `LC_COLLATE=C`.

**Comment by BjornFJohansson** [comment]
added test_sort_order() in test_manip.py.
