### ISSUE TITLE
ROBUSTNESS: Remove 'prefix' from API

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#40]
DECISION 2023-12-19: Yes, be conservative and remove/hardcode it for now:

* [x] R
* [ ] Python

**Comment by BjornFJohansson** [comment]
Doable, but require rewrite because of how some functions call others.

**Comment by HenrikBengtsson** [comment]
> Doable, but require rewrite because of how some functions call others.

Exactly.  I resorted to the following hack:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/56ee58ad0dad0a1780b00947ff9564f9d2a3e930/r/R/chksum.R#L95

where:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/56ee58ad0dad0a1780b00947ff9564f9d2a3e930/r/R/chksum.R#L17-L19

**Comment by BjornFJohansson** [comment]
done!
