### ISSUE TITLE
Validate input, e.g. seguid("123") should give an error

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#5]
Currently, we don't validate input, e.g.

```r
> seguid("123")
[1] "QL0AFWMIX8NRZTKeof9cXsvbvu8"
```

At a minimum, I think we should assert that the input is a valid biological sequence.

**Comment by HenrikBengtsson** [comment]
There could be internal helper functions `is_dna_sequence()` and `is_protein_sequence()`.  The `seguid()` and `useguid()` can assert that either of those are met.  `lseguid()` and `cseguid()` will assert toward `is_dna_sequence()` only.

Also, `lseguid(watson, cricket)` should assert that `watson` and `cricket` are actually compatible, reverse complements.

**Comment by HenrikBengtsson** [comment]
I don't think one should allow mixed lower- and upper-case sequences, e.g. `aaCt`.  It should either be all lower case or all upper case, but not mixed.  By giving an error for the mixed case, one lowers the risk for cut'n'paste mistakes.

**Comment by BjornFJohansson** [comment]
This is now current behaviour:

```
slseguid("234")
Traceback (most recent call last):

  Cell In[3], line 1
    slseguid("234")

  File ~/Desktop/ProjectCheckSum/seguid/Python/src/seguid/chksum.py:211 in slseguid
    return _seguid(seq,

  File ~/Desktop/ProjectCheckSum/seguid/Python/src/seguid/chksum.py:137 in _seguid
    assert_in_alphabet(seq, alphabet=set(table.keys()))

  File ~/Desktop/ProjectCheckSum/seguid/Python/src/seguid/asserts.py:31 in assert_in_alphabet
    raise ValueError(

ValueError: Detected symbols 3 2 4 in not in the 'alphabet'
```
