### ISSUE TITLE
RESTRUCTURE: src/seguid/ -> seguid/?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#50]
Is there a specific reason (de-facto standard?) for having `src/seguid/`, and not just `seguid/`?

**Comment by BjornFJohansson** [comment]
Yes! It makes it easier to run tests on the installed code instead of the code in the package:

https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/
