### ISSUE TITLE
Is the xxseguid:NNN as url-safe as the original encoding?

### ISSUE THREAD

**Issue by BjornFJohansson** [MetabolicEngineeringGroupCBMA/seguid#52]
The colon : intoduced between the type and the checksum does work for local files on a modern browser.
It is however listed as "reserved" in the standard below. We might consider changing it.

Now:

	slseguid:Ax_RG6hzSrMEEWoCO1IWMGska-4

Future safe(er) alternatives:

	slseguid-Ax_RG6hzSrMEEWoCO1IWMGska-4     Uses a char already in the encoding alphabet
	slseguid_Ax_RG6hzSrMEEWoCO1IWMGska-4     -"-
	slseguid#Ax_RG6hzSrMEEWoCO1IWMGska-4     Uses "punctuation" from below

Interestingly the "+" is listed as a safe char below, but is one that is removed in the base64url encoding.

```


Berners-Lee, Masinter & McCahill                               [Page 19]

[RFC 1738](https://www.ietf.org/rfc/rfc1738.txt)         Uniform Resource Locators (URL)        December 1994


alpha          = lowalpha | hialpha
digit          = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" |
                 "8" | "9"
safe           = "$" | "-" | "_" | "." | "+"
extra          = "!" | "*" | "'" | "(" | ")" | ","
national       = "{" | "}" | "|" | "\" | "^" | "~" | "[" | "]" | "`"
punctuation    = "<" | ">" | "#" | "%" | <">


reserved       = ";" | "/" | "?" | ":" | "@" | "&" | "="
hex            = digit | "A" | "B" | "C" | "D" | "E" | "F" |
                 "a" | "b" | "c" | "d" | "e" | "f"
escape         = "%" hex hex

unreserved     = alpha | digit | safe | extra
uchar          = unreserved | escape
xchar          = unreserved | reserved | escape
digits         = 1*digit

```

**Comment by HenrikBengtsson** [comment]
There's also the file system to worry about. MS Windows doesn't allow colons in path names, because colon is used for the drive space.

**Comment by HenrikBengtsson** [comment]
DECISION:

* [ ] Explicitly declare support for URLs, pathnames, and key-value pairs in programming languages
* [ ] Add unit tests for writing and reading to temporary files where filenames are SEGUID checksums.
* [ ] Run GitHub Actions tests on Linux, macOS, and MS Windows.
* [ ] For now, switch `:` to `-` (might revisit later)
