### ISSUE TITLE
Python: GitHub Actions fails right now

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#54]
From https://github.com/MetabolicEngineeringGroupCBMA/seguid/actions/runs/7364986549/job/20045856474:

```
FAILED tests/test_manip.py::test_min_rotation_pydivsufsort - ModuleNotFoundError: No module named 'pydivsufsort'
========================= 1 failed, 29 passed in 0.19s =========================
Error: Process completed with exit code 1.
```

Try to avoiding leaving broken code on GitHub, because it's a blocker from pushing new commits; if one push it might be even harder to track down and fix the original problem.

**Comment by BjornFJohansson** [comment]
fixed
