### ISSUE TITLE
Language-agnostic way of specifying table

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#58]
In Python, we have used `dict` for custom complementary tables, in R we have used named vectors. This means, we have to document each differently.

Also, neither works when using the CLI API.

I'd like to propose a language-agnostic syntax. Maybe a string, e.g.

```
table="AT,TA,CG,GC"
```

One could also imagine extending an existing set, e.g. `"{DNA},au,ua"`

**Comment by BjornFJohansson** [comment]
Could be a good idea.

**Comment by HenrikBengtsson** [comment]
Moved to the remaining tasks to #62 .
