### ISSUE TITLE
IDEA: Consider SHA-2

### ISSUE THREAD

**Issue by BjornFJohansson** [MetabolicEngineeringGroupCBMA/seguid#59]
Future proofing "SEGUID". Important consideration is checksum length, GenBank files have limited
width.

GenBank files seem to accept ~67 chars before line break, looking at the [sample record](https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html) above, counting chars.

**Comment by HenrikBengtsson** [comment]
* [SHA-1](https://en.wikipedia.org/wiki/SHA-1): 160 bits = 20 bytes = 40 hexadecimal character
* [SHA-2](https://en.wikipedia.org/wiki/SHA-2)/SHA-256: 256 bits = 32 bytes = 64 hexadecimal character = 60% longer than SHA-1

**Comment by BjornFJohansson** [comment]
Genbank formatted text files with 68 or 80 chars comment made with Biopython.
```
LOCUS       name                       3 bp    DNA              UNK 01-JAN-1980
DEFINITION  .
ACCESSION   id
VERSION     id
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
COMMENT     1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij12345678
FEATURES             Location/Qualifiers
ORIGIN
        1 aaa
//

LOCUS       name                       3 bp    DNA              UNK 01-JAN-1980
DEFINITION  .
ACCESSION   id
VERSION     id
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
COMMENT     
            1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij1234567890abcdefghij
FEATURES             Location/Qualifiers
ORIGIN
        1 aaa
//
```

**Comment by HenrikBengtsson** [comment]
We considered it, but decided to stay with SHA-1. Reasons will be explained in manuscript.
