### ISSUE TITLE
lseguid(): combine lseguid_blunt() and lseguid_sticky()

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#6]
I think one can combine `lseguid_blunt()` and `lseguid_sticky()` into a single function `lseguid()`; `lseguid_sticky()` basically does all the heavy lifting already and `lseguid_blunt(seq)` == `lseguid_sticky(seq, rc(seq), overhang = 0)`

**Comment by BjornFJohansson** [comment]
dsseguid!
