### ISSUE TITLE
dcSEGUID:  Generalized version. Retain complementary strand in calculation.

### ISSUE THREAD

**Issue by BjornFJohansson** [MetabolicEngineeringGroupCBMA/seguid#60]
Consider a new rotate_to_min function that handles both strands at the same time. Code as is readable as is, but the information in one of the strads is not used. This is not a problem as long as there is a well defined and reciprocal alphabet. The algorithm could be made more general if both complementary strands are rotated at the same time instead of rotating one or the other.

**Comment by BjornFJohansson** [comment]
See commit e01baccb460cd658bef2148bd2dc65c635459c10

**Comment by HenrikBengtsson** [comment]
I've moved these updates to the [`feature/rotate_ds_to_min`](https://github.com/MetabolicEngineeringGroupCBMA/seguid/tree/feature/rotate_ds_to_min) branch, and reset the `main` branch to the commit prior to these updates.

As far as I understand it, the gist of your proposal is to have a rotation function:

```
rotate_ds_to_min(seq1, seq2)
```

that rotates sequence `seq1` to its minimal representation, and `seq2` the same amount in the opposite direction.  Importantly, **`seq1` and `seq2` does _not_ have to be reverse complementary.**  I think it would be useful to show an illustration where such a incompatible double-stranded rotation is needed.

**Comment by HenrikBengtsson** [comment]
I'm trying to come up with a circular dsDNA case, where I allow the complementary alphabet to be _non-bijective_ (e.g. `A<->T` and `A<->U`), and where the Crick strand makes a difference in the minimal rotation.  I'm not sure such an example exists; I'm leaning towards all necessary information to identify the minimal rotation is always in the Watson strand, regardless of the Crick strand.

**Comment by BjornFJohansson** [comment]
Upper/lower case has no meaning in examples below other than indicating the origin of the nucleotides. The pcr product is physically made from the pcr primers and the nucleotide building blocks.

### Normal PCR

    gat (fp)

    ttg (rp)

    GATTACAA (watson)
    CTAATGTT (crick)

---

nucleotide building blocks: g a t c


    GATTACAA w
         ||| 
        <gtt
    gat>
    |||     
    CTAATGTT c

Result:

    gattacaa
    ctaatgtt

ligate, so molecule is circular. smallest rotations:

    aagattac
    ttctaatg

    aatcttgt
    ttagaaca

first is smaller. 
Argument to hash function, crick generated from watson in the fly

    aagattac\nttctaatg  

Here, the second strand can be regenerated in hash function without any problems
since alphabet is "bijective" i.e. watson and crick strands completely determine each other.


### PCR with one uridine in reverse primer [overview](https://en.wikipedia.org/wiki/Nucleoside#List_of_nucleosides_and_corresponding_nucleobases) 

    gat (fp)

    utg (rp)

    GATTACAA (watson)
    CTAATGTT (crick)

---

nucleotide building blocks: g a t c

    GATTACAA w
         ||| 
        <gtu
    gat>
    |||     
    CTAATGTT c


    gattacaa
    ctaatgtu

ligate, so molecule is circular. smallest rotations:

    aagattac
    tuctaatg

    aatcutgt
    ttagaaca

first is smaller. 
Argument to hash function, **crick generated from watson in the fly**.

    aagattac\nttctaatg

This is the exact same argument as in the previous example.

A better argument would be:

    aagattac\ntuctaatg

For this, it is practical to rotate the watson and crick at the same time.

This does not mean that crick influences the position of the smallest rotation
of watson, only that both sequences fed into the function should be used
in calculation of the final checksum in the case alphabet is not bijective.

**Comment by BjornFJohansson** [comment]
Uracil in DNA occurs naturally:  https://en.wikipedia.org/wiki/Uracil

Uracil-containing DNA still exists, for example in

- DNA of several [phages](https://en.wikipedia.org/wiki/Phage)[[15]](https://en.wikipedia.org/wiki/Uracil#cite_note-15)
- [Endopterygote](https://en.wikipedia.org/wiki/Endopterygote) development
- Hypermutations during the synthesis of vertebrate antibodies.[[citation needed](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)]

**Comment by HenrikBengtsson** [comment]
Oh/ah, you probably said this in our early January meeting, but since then my interpretation of the problem morphed into a different interpretation.

So, you're concerned about the `crick = rc(watson)` in:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/d5e0cd89753653651e7efd56effecd5f4bf4d321/python/src/seguid/chksum.py#L260

I though you were saying that:

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/d5e0cd89753653651e7efd56effecd5f4bf4d321/python/src/seguid/chksum.py#L254

is not sufficient and that we needed something like:

```python
    if (watson_min_1, crick_min_1) < (crick_min_2, watson_min_2)
```

I agree that we must not use `rc()`, and therefore we need to work with co-rotation of (watson,crick) and co-rotation of (crick,watson).

**Comment by HenrikBengtsson** [comment]
I've now reverted the back to almost the original - I think the single-strand comparison is still new;

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/1d9fe3ff4a9218f863cc869d504581abb8c5d023/python/src/seguid/chksum.py#L242-L253

https://github.com/MetabolicEngineeringGroupCBMA/seguid/blob/1d9fe3ff4a9218f863cc869d504581abb8c5d023/r/R/chksum.R#L251-L264

Now, I think we're ready to open up for non-bijective complementary languages.
