### ISSUE TITLE
ambiguous_dna_complement: What does "ambiguous" refer to?

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#7]
What does "ambiguous" refer to in `ambiguous_dna_complement()`?

**Comment by BjornFJohansson** [comment]
Some letter can have an ambiguous meaning, for example N = G,A,C or T

<center>

IUPAC Code | Meaning
-- | --
A | T
C | G
G | C
T | A
A or C | K
A or G | Y
A or T | W
C or G | S
C or T | R
G or T | M
A or C or G | B
A or C or T | D
A or G or T | H
C or G or T | V
G or A or T or C | N

</center><p><br style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
