### ISSUE TITLE
reverse complementary for RNA strands

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#8]
In line with some of the comments in #5 , we need to be able to distinguish between DNA and RNA such that `rc()` produces the correct result given a DNA and an RNA sequence.

Alternatively, one could punt on support for RNA sequences by not allowing them at all.

**Comment by BjornFJohansson** [comment]
A new table in tables.py (not pushed yet)

```
# Definition of Complementary RNA Symbols
COMPLEMENT_TABLE_RNA = {"G": "C",
                        "A": "U",
                        "C": "G",
                        "U": "A"}
```
