### ISSUE TITLE
Python: Set up CI testing via GitHub Actions

### ISSUE THREAD

**Issue by HenrikBengtsson** [MetabolicEngineeringGroupCBMA/seguid#9]
Set up CI testing on the Python via GitHub Actions.  See https://github.com/HenrikBengtsson/port4me for an example.

**Comment by HenrikBengtsson** [comment]
Added, cf. commit 50bf86bcaf.  Adopted from https://github.com/HenrikBengtsson/port4me/blob/develop/.github/workflows/check-python.yml.

**Comment by BjornFJohansson** [comment]
seems to work now.
